### ISSUE TITLE
one tiny thing

### ISSUE THREAD

**Issue by Ultrunz** [xander1998/dashcam#2]
first off script is amazing, i love it.

i have one small problem, the time is displayed i guess as europe time. not my actual computer time.

I have looked through the code as i repositioned the UI around my existing one. I'm not sure exactly whats happened here but its confused me :P

![image](https://user-images.githubusercontent.com/13288425/45283828-1d8e5380-b509-11e8-9ec2-3aaac640bbed.png)

![image](https://user-images.githubusercontent.com/13288425/45283841-254df800-b509-11e8-9dc4-17ab3c8b295f.png)

**Comment by KingRyuShin** [comment]
The time that is taken is the one from the machine the server is hosted on and not your own computer

**Comment by xander1998** [comment]
Thats not an issue that is how its supposed to be.
